# -*- coding: utf-8 -*-
"""MockUp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/144xse41EnPnpBToF4LOrN9yCFVvQIT-p
"""

# Bio-Quantum Tactile Architecture Mockup
# Runs on Google Colab

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))

# Node positions
nodes = {
    "User\n(Brain Signal)": (0.5, 3),
    "Neural Interface": (2.5, 3),
    "BQTA Core\n(Bio-Quantum Processor)": (5, 3),
    "Quantum Network": (7.5, 3),
    "Robotic Arm": (10, 3),
    "Haptic Feedback": (5, 1)
}

# Draw nodes
for label, (x, y) in nodes.items():
    plt.scatter(x, y, s=2000)
    plt.text(x, y, label, ha='center', va='center', fontsize=10)

# Draw arrows
arrows = [
    ("User\n(Brain Signal)", "Neural Interface"),
    ("Neural Interface", "BQTA Core\n(Bio-Quantum Processor)"),
    ("BQTA Core\n(Bio-Quantum Processor)", "Quantum Network"),
    ("Quantum Network", "Robotic Arm"),
    ("Robotic Arm", "Haptic Feedback"),
    ("Haptic Feedback", "BQTA Core\n(Bio-Quantum Processor)")
]

for start, end in arrows:
    x1, y1 = nodes[start]
    x2, y2 = nodes[end]
    plt.arrow(x1, y1, x2-x1, y2-y1,
              length_includes_head=True,
              head_width=0.15,
              head_length=0.25)

plt.title("Bio-Quantum Tactile Architecture (BQTA) — Mockup")
plt.axis('off')
plt.show()