# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1quHIMcfnxXZdHZCSiAv2f-z3SqXl1opH
"""

# ==============================
# BQTA Advanced Live Mockup (A+)
# ==============================

import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact, FloatSlider, IntSlider, Checkbox
from IPython.display import display

# Enable widgets in Colab
try:
    from google.colab import output
    output.enable_custom_widget_manager()
except:
    pass


def bqta_sim(user_force=5, latency_ms=20, packet_loss=10, ai_prediction=True):

    print("=== BQTA Closed-Loop Simulation ===")
    print(f"User Force: {user_force}")
    print(f"Latency: {latency_ms} ms")
    print(f"Packet Loss: {packet_loss}%")
    print(f"AI Prediction: {ai_prediction}")
    print("------------------------------------")

    t = np.linspace(0, 1, 100)

    # User → Robotic Arm
    robotic_signal = user_force * np.sin(2 * np.pi * t)

    # Latency simulation
    delay = int(latency_ms / 5)
    delayed_signal = np.roll(robotic_signal, delay)

    # Packet loss simulation
    mask = np.random.rand(len(delayed_signal)) > (packet_loss / 100)
    received = delayed_signal * mask

    # AI Prediction (simple recovery)
    if ai_prediction:
        for i in range(1, len(received)):
            if received[i] == 0:
                received[i] = received[i-1]

    # Haptic feedback
    feedback = received + np.random.normal(0, 0.1, len(received))

    # Single Plot (ตามกติกา)
    plt.figure()
    plt.plot(t, robotic_signal)
    plt.plot(t, feedback)
    plt.title("BQTA Closed-Loop Signal Simulation")
    plt.xlabel("Time")
    plt.ylabel("Signal")
    plt.show()


interact(
    bqta_sim,
    user_force=FloatSlider(min=1, max=10, step=1, value=5),
    latency_ms=IntSlider(min=0, max=100, step=5, value=20),
    packet_loss=IntSlider(min=0, max=50, step=5, value=10),
    ai_prediction=Checkbox(value=True, description="Enable AI Prediction")
)